//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int record_id { get; set; }
        public int alumni_id { get; set; }
        public string secondaryemail { get; set; }
        public string Campus { get; set; }
        public string skill_1 { get; set; }
        public string skill_2 { get; set; }
        public string skill_3 { get; set; }
        public string programfast { get; set; }
        public Nullable<System.DateTime> graduationdate { get; set; }
        public string password { get; set; }
        public string comment { get; set; }
    
        public virtual linkedinAccount linkedinAccount { get; set; }
    }
}
